server:
  port: 8082
  servlet:
    context-path: /getway

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defautZone:  http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: course
          uri: lb://course
          predicates:
            - Path=/course