server:
  port: 8080
  servlet:
    context-path: /getway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000