server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defautZone:  http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: course
  profiles:
    active: development
  security:
    user:
      name: user
      password: user

datasource:
  drive-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 123456

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug


